### ISSUE TITLE
WiFi Bluetooth Combo Card

### ISSUE THREAD

**Issue by Eshatos** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#1]
Hello, first of all: Awesome work!!!!

Thank you a Lot, i was able get through the Installation on my machine. without any trouble.
Have you replaced the internal wifi card by any Broadcom modell? Wich one would you recommend?

Greetings and thumbs up!

**Comment by gajjartejas** [comment]
Added wireless buying guide:
[https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/WIRELESS_CARD_BUYING_GUIDE.md](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/WIRELESS_CARD_BUYING_GUIDE.md)
