### ISSUE TITLE
Upgrading to Catalina

### ISSUE THREAD

**Issue by VincentAA** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#10]
I was trying to upgrade to Catalina from Mojave but it stuck on
apfs_module_start:1683: load: com.apple.filesystems.apfs, v1412.11.7, apfs-1412.11.7, 2019/09/26
I tried to use the updated clover files but i get kernel panic. tried to use the SSDT from the updated clover with my regular clover files also stuck on apfs_module_start
any idea how to fix it?

**Comment by gajjartejas** [comment]
Do not update clover. There are some issues with the latest clover. You have to use my latest Catalina clover to upgrade. You have to change lilucpu=x according it.

**Comment by VincentAA** [comment]
I think it's something related to EC device. any idea how u changed or renamed the EC device to get it working, 
also does the SSDT-I320.aml enables touchpad and brightness keys? i tried it with mojave and it didn't work does it require ddst to be with it?

**Comment by VincentAA** [comment]
I fixed it by using SSDT-EC.aml and lilucpu=8,
I still don't know what SSDT-I320.aml does it doesn't enable touchpad

**Comment by gajjartejas** [comment]
Hello @VincentAA There are ACPI patches in my latest colver folder
```
change EC0 to EC
4543305f 
45435f5f 

change H_EC to EC
485f4543 
45435f5f 
```
Yes, SSDT-I320.aml enables touchpad and brightness keys, You need some ACPI patches in config.plist

For touchpad have you tried? 
https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/10.15.x/10.15/CLOVER.zip

If not works for touchpad can you please confirm you have the same laptop Ideapad 320 15ISK? If you don't mine you can share your clover folder here.

**Comment by VincentAA** [comment]
I have those ACPI patches on my ACPI, I tried to use ur config.plist but it gives me kernel panic
Yes i have Lenovo ideapad 350 15ISK

Heres my clover folder https://drive.google.com/file/d/1m5D9zJuzohLLarIG7K17BT-ixvmkjDTS/view?usp=sharing

**Comment by VincentAA** [comment]
@gajjartejas please reply asap i still can't get the SSDT-I320.aml to work, it's like not being patched but it's loaded in MacASL menu or shown on clover menu settings, but the touchpad and the brightness keys doesn't work

**Comment by gajjartejas** [comment]
Hello @VincentAA sorry for late reply have you tried my touchpad guide?

**Comment by longpos222** [comment]
Hello @gajjartejas, I have the same model like you and now I get stuck at this when up to 10.15.5. Could you please give me some advice? Thankss

**Comment by longpos222** [comment]
![IMG_20200611_193604_144](https://user-images.githubusercontent.com/35419213/84390334-9b711880-ac21-11ea-8735-bfac34fc2ee5.jpg)
Here is my error.
