### ISSUE TITLE
Will these work with lenovo ideapad 320 15ikb 81bg?

### ISSUE THREAD

**Issue by Stevemoretz** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#15]
Hi will they?I need to get my battery working.How can I do that please help me thank you.How do you do it on Lenovo-Ideapad-320-15ISK-14ISK? Is there any patch for battery?

**Comment by gajjartejas** [comment]
You could try ACPIBatteryManager.kext

**Comment by Stevemoretz** [comment]
Very nice I'll try that thank you so much.
The tutorial you put the link about graphics enabling.is too hard for regular people who don't hackintosh a lot.(just like me,I'm just a programmer who needs macos to develop ios apps)
Would you please provide some easy steps what shall I do?
Lenovo-Ideapad-320-15ISK-14ISK's graphics card is Intel UHD 620 and it's giving me 7mb of gpu memory.Would you please help me fix that?
Searched all over the internet not an easy example I even lost my config.plist while doing one of the tutorials which made me reinstall the whole hackintosh.Thanks so much in advance

**Comment by gajjartejas** [comment]
Sure, you could send me your clover folder.

**Comment by Stevemoretz** [comment]
Awesome thank you so much I just noticed my hackintosh is gone again after doing one other tutorial yesterday I need to reinstall it.And then I'll send the clover folder thank you so much again you're a life saver.I really need macos to keep my job but already paid 1000$ for the lenovo I don't have more money to buy a mac.Again thank you so much dude.

**Comment by Stevemoretz** [comment]
@gajjartejas 
Hi how are you?I was trying to get the catalina installed and then get it with windows in dual boot.Sorry for being late but it took me some time.And Finally I'm up and running catalina.

This is my Clover folder + a few screenshots
[](https://drive.google.com/file/d/1db-gdwmex_s59l4W0-_SxYPjwrszrj3u/view?usp=sharing)

the most important things to me that are not working:

- Graphics memory used to be 7mb on mojave.But on catalina is doesn't show it in about this mac menu I included a picture of about us.I think it also thinks my gpu is nvidea.But my main gpu is intel uhd 620(the second screenshot).
-The brightness doesn't work.I really need it.Cause I use my pc a lot (I'm a programmer just like you).and my eyes are sensitive.I was thinking fixing the graphics could fix this too.

That's seriously what I really need and can't live without just the brightness and making sure gpu is working fine.

But also these things don't work too if I could fix them that could be nice.
-Sleep not working.
-Trackpad not working.
-Audio works for headphone and htmi but not for the speaker.

Just to mention I'm a noob in these stuff.So please tell me also how to backup stuff before I do them and how to restore because I have managed to blow my hackintosh by following some tutorials serveral times but couldn't get it fixed and had to reinstall and so much pain through.

just to mention that clover folder I haven't setup anything by myself I bought it from somebody who said this will do the most of the job for me.So I haven't installed anything any kext by myself it was just in the package.

Thank you so much for your kindness and help.I really need it I'm not just playing around for fun.This is my job and I need to save it with this.You are so generous and kind.
Everything else is working perfectly.

**Comment by Stevemoretz** [comment]
Hi Oh Sorry I noticed the link hasn't been attached to the text now.
This is my clover + the screen shots I told you about.
https://drive.google.com/file/d/1db-gdwmex_s59l4W0-_SxYPjwrszrj3u/view?usp=sharing
All I need is to get the intel uhd 620 gpu working.That's all thank you so much for you help in advance.

**Comment by gajjartejas** [comment]
@Stevemoretz Thanks I will check it.

**Comment by Stevemoretz** [comment]
@gajjartejas  No thank you. so much!I really appriciate your help.

**Comment by Stevemoretz** [comment]
Hi again I managed to bring the gpu on about this mac buy pressing add InjectIntel and FakeID=0x12345678 video card work but video ram =7 mb.
But now only 7mb.
I found a tutorial using hackintool we can generate a patch and put in under devices section in properties.

https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/

I have intel uhd 620 but hackintool has only intel hd 620 and intel uhd630 so I went with uhd 630 as the tutorial said it was closer.What I got was a black screen and restart.

Here's my config.plist after doing the tutorial:

`<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>
				CQCSPg==
				</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>
				mz4AAA==
				</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>model</key>
				<string>???</string>
			</dict>
		</dict>`

**Comment by Stevemoretz** [comment]
By choosing intel hd 620 I fixed the problem!
Now my graphics is working but the brightness isn't I need to fix that too.

**Comment by Stevemoretz** [comment]
I also got that working the last thing is to fix power problem.My hackintosh is using too much battery.
 I installed Intel power gadget on both windows and hackintosh here they are: windows idle: Imgur hackintosh idle: Imgur

hackintosh going in different settings closing and opening the browser just to do something: Imgur

Do they seem normal?

How can I check if the problem is my second gpu? (I have an intel integerated and nvidea discrete).I want to make sure my nvidea isn't on and consuming power.

**Comment by gajjartejas** [comment]
I will look into it in weekend

**Comment by edergilson** [comment]
Hey man, can you provide your EFI folder? I have the same notebook as yours, but after Catalina install, when I'm creating a user and setting up the Mac, it reboots itself.

**Comment by gajjartejas** [comment]
@Stevemoretz Please provide your clover to @edergilson  if everything working fine.

**Comment by Stevemoretz** [comment]
Hi this is my clover
https://drive.google.com/file/d/1db-gdwmex_s59l4W0-_SxYPjwrszrj3u/view?usp=sharing

It's based on a distro called Niresh so you may not like it but it works
