### ISSUE TITLE
Trouble getting touchpad working

### ISSUE THREAD

**Issue by Stevemoretz** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#16]
Hi thank you for your brilliant repo.
I have a ideapad 320 15ikb 81bg.
I am trying to follow your guide here:
https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/Touchpad-Guide.md
Pressed f4 and here's the list of my files:

```
`-rwxrwxrwx  1 steve  admin     188 Mar 18 08:41 APIC.aml
-rwxrwxrwx  1 steve  admin     165 Mar 18 08:41 ASF!.aml
-rwxrwxrwx  1 steve  admin      52 Mar 18 08:41 ASPT.aml
-rwxrwxrwx  1 steve  admin      56 Mar 18 08:41 BGRT.aml
-rwxrwxrwx  1 steve  admin      40 Mar 18 08:41 BOOT.aml
-rwxrwxrwx  1 steve  admin      84 Mar 18 08:41 DBG2.aml
-rwxrwxrwx  1 steve  admin      52 Mar 18 08:41 DBGP.aml
-rwxrwxrwx  1 steve  admin     204 Mar 18 08:41 DMAR.aml
-rwxrwxrwx  1 steve  admin  117780 Mar 18 08:41 DSDT.aml
-rwxrwxrwx  1 steve  admin     268 Mar 18 08:41 FACP.aml
-rwxrwxrwx  1 steve  admin      64 Mar 18 08:41 FACS.aml
-rwxrwxrwx  1 steve  admin      68 Mar 18 08:41 FPDT.aml
-rwxrwxrwx  1 steve  admin      56 Mar 18 08:41 HPET.aml
-rwxrwxrwx  1 steve  admin     148 Mar 18 08:41 LPIT.aml
-rwxrwxrwx  1 steve  admin      60 Mar 18 08:41 MCFG.aml
-rwxrwxrwx  1 steve  admin      85 Mar 18 08:41 POAT.aml
-rwxrwxrwx  1 steve  admin      36 Mar 18 08:41 RSDP.aml
-rwxrwxrwx  1 steve  admin     148 Mar 18 08:41 RSDT.aml
-rwxrwxrwx  1 steve  admin    1219 Mar 18 08:41 SSDT-0-CB-01.aml
-rwxrwxrwx  1 steve  admin      70 Mar 18 08:41 SSDT-1-CB-01.aml
-rwxrwxrwx  1 steve  admin   12536 Mar 18 08:41 SSDT-2-CB-01.aml
-rwxrwxrwx  1 steve  admin     671 Mar 18 08:41 SSDT-3-CB-01.aml
-rwxrwxrwx  1 steve  admin     838 Mar 18 08:41 SSDT-4-CB-01.aml
-rwxrwxrwx  1 steve  admin    3649 Mar 18 08:41 SSDT-5-CB-01.aml
-rwxrwxrwx  1 steve  admin    1310 Mar 18 08:41 SSDT-6-CB-01.aml
-rwxrwxrwx  1 steve  admin    4272 Mar 18 08:41 SSDT-7-CB-01.aml
-rwxrwxrwx  1 steve  admin    3806 Mar 18 08:41 SSDT-8-CB-01.aml
-rwxrwxrwx  1 steve  admin    1485 Mar 18 08:41 SSDT-x8_0-Cpu0Ist.aml
-rwxrwxrwx  1 steve  admin    1628 Mar 18 08:41 SSDT-x8_1-ApIst.aml
-rwxrwxrwx  1 steve  admin    1023 Mar 18 08:41 SSDT-x8_2-Cpu0Cst.aml
-rwxrwxrwx  1 steve  admin     394 Mar 18 08:41 SSDT-x8_3-ApCst.aml
-rwxrwxrwx  1 steve  admin     277 Mar 18 08:41 SSDT-x8_4-Cpu0Hwp.aml
-rwxrwxrwx  1 steve  admin     407 Mar 18 08:41 SSDT-x8_5-ApHwp.aml
-rwxrwxrwx  1 steve  admin     420 Mar 18 08:41 SSDT-x8_6-HwpLvt.aml
-rwxrwxrwx  1 steve  admin      52 Mar 18 08:41 TPM2.aml
-rwxrwxrwx  1 steve  admin      66 Mar 18 08:41 UEFI.aml
-rwxrwxrwx  1 steve  admin      40 Mar 18 08:41 WSMT.aml
-rwxrwxrwx  1 steve  admin     260 Mar 18 08:41 XSDT.aml`
```

tried this code:

> iasl -da -dl *.aml

But it doesn't work :
```
steve@steve origin % iasl -da -dl *.aml

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180427(RM)
Copyright (c) 2000 - 2018 Intel Corporation

Input file APIC.aml, Length 0xBC (188) bytes
ACPI: APIC 0x0000000000000000 0000BC (v03 LENOVO CB-01    00000001 ACPI 00040000)
External object resolution file         XSDT.aml
Input file XSDT.aml, Length 0x104 (260) bytes
    XSDT.aml: Table [XSDT] is not an AML table - ignoring
External object resolution file         WSMT.aml
Input file WSMT.aml, Length 0x28 (40) bytes
    WSMT.aml: Table [WSMT] is not an AML table - ignoring
External object resolution file         UEFI.aml
Input file UEFI.aml, Length 0x42 (66) bytes
    UEFI.aml: Table [UEFI] is not an AML table - ignoring
External object resolution file         TPM2.aml
Input file TPM2.aml, Length 0x34 (52) bytes
    TPM2.aml: Table [TPM2] is not an AML table - ignoring
External object resolution file SSDT-x8_6-HwpLvt.aml
Input file SSDT-x8_6-HwpLvt.aml, Length 0x1A4 (420) bytes
ACPI: SSDT 0x0000000000000000 0001A4 (v02 PmRef  HwpLvt   00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_5-ApHwp.aml
Input file SSDT-x8_5-ApHwp.aml, Length 0x197 (407) bytes
ACPI: SSDT 0x0000000000000000 000197 (v02 PmRef  ApHwp    00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_4-Cpu0Hwp.aml
Input file SSDT-x8_4-Cpu0Hwp.aml, Length 0x115 (277) bytes
ACPI: SSDT 0x0000000000000000 000115 (v02 PmRef  Cpu0Hwp  00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_3-ApCst.aml
Input file SSDT-x8_3-ApCst.aml, Length 0x18A (394) bytes
ACPI: SSDT 0x0000000000000000 00018A (v02 PmRef  ApCst    00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_2-Cpu0Cst.aml
Input file SSDT-x8_2-Cpu0Cst.aml, Length 0x3FF (1023) bytes
ACPI: SSDT 0x0000000000000000 0003FF (v02 PmRef  Cpu0Cst  00003001 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_1-ApIst.aml
Input file SSDT-x8_1-ApIst.aml, Length 0x65C (1628) bytes
ACPI: SSDT 0x0000000000000000 00065C (v02 PmRef  ApIst    00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-x8_0-Cpu0Ist.aml
Input file SSDT-x8_0-Cpu0Ist.aml, Length 0x5CD (1485) bytes
ACPI: SSDT 0x0000000000000000 0005CD (v02 PmRef  Cpu0Ist  00003000 INTL 20160527)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-8-CB-01.aml
Input file SSDT-8-CB-01.aml, Length 0xEDE (3806) bytes
ACPI: SSDT 0x0000000000000000 000EDE (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-7-CB-01.aml
Input file SSDT-7-CB-01.aml, Length 0x10B0 (4272) bytes
ACPI: SSDT 0x0000000000000000 0010B0 (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-6-CB-01.aml
Input file SSDT-6-CB-01.aml, Length 0x51E (1310) bytes
ACPI: SSDT 0x0000000000000000 00051E (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-5-CB-01.aml
Input file SSDT-5-CB-01.aml, Length 0xE41 (3649) bytes
ACPI: SSDT 0x0000000000000000 000E41 (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-4-CB-01.aml
Input file SSDT-4-CB-01.aml, Length 0x346 (838) bytes
ACPI: SSDT 0x0000000000000000 000346 (v01 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-3-CB-01.aml
Input file SSDT-3-CB-01.aml, Length 0x29F (671) bytes
ACPI: SSDT 0x0000000000000000 00029F (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-2-CB-01.aml
Input file SSDT-2-CB-01.aml, Length 0x30F8 (12536) bytes
ACPI: SSDT 0x0000000000000000 0030F8 (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-1-CB-01.aml
Input file SSDT-1-CB-01.aml, Length 0x46 (70) bytes
ACPI: SSDT 0x0000000000000000 000046 (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file SSDT-0-CB-01.aml
Input file SSDT-0-CB-01.aml, Length 0x4C3 (1219) bytes
ACPI: SSDT 0x0000000000000000 0004C3 (v02 LENOVO CB-01    00000001 ACPI 00040000)
Pass 1 parse of [SSDT]
Pass 2 parse of [SSDT]
External object resolution file         RSDT.aml
Input file RSDT.aml, Length 0x94 (148) bytes
    RSDT.aml: Table [RSDT] is not an AML table - ignoring
External object resolution file         RSDP.aml
Input file RSDP.aml, Length 0x24 (36) bytes
```

looking at here it says:

> https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/

> For newer ACPI sets (usually [but not always] with Skylake and later), there is no need for -da as they have embedded External opcodes:

So I emitted -da.
and used:

> iasl -dl DSDT.aml SSDT*.aml

I get:
```
Parsing completed
Disassembly completed

```

here's the list of disassembled files:

> steve@steve origin % ls -l *.dsl                
> -rw-r--r--  1 steve  admin  877917 Mar 18 12:36 DSDT.dsl
> -rw-r--r--  1 steve  admin   10504 Mar 18 12:36 SSDT-0-CB-01.dsl
> -rw-r--r--  1 steve  admin     841 Mar 18 12:36 SSDT-1-CB-01.dsl
> -rw-r--r--  1 steve  admin   80990 Mar 18 12:36 SSDT-2-CB-01.dsl
> -rw-r--r--  1 steve  admin    5253 Mar 18 12:36 SSDT-3-CB-01.dsl
> -rw-r--r--  1 steve  admin    6218 Mar 18 12:36 SSDT-4-CB-01.dsl
> -rw-r--r--  1 steve  admin   18707 Mar 18 12:36 SSDT-5-CB-01.dsl
> -rw-r--r--  1 steve  admin   12343 Mar 18 12:36 SSDT-6-CB-01.dsl
> -rw-r--r--  1 steve  admin   13266 Mar 18 12:36 SSDT-7-CB-01.dsl
> -rw-r--r--  1 steve  admin   19258 Mar 18 12:36 SSDT-8-CB-01.dsl
> -rw-r--r--  1 steve  admin   10971 Mar 18 12:36 SSDT-x8_0-Cpu0Ist.dsl
> -rw-r--r--  1 steve  admin   11099 Mar 18 12:36 SSDT-x8_1-ApIst.dsl
> -rw-r--r--  1 steve  admin    7401 Mar 18 12:36 SSDT-x8_2-Cpu0Cst.dsl
> -rw-r--r--  1 steve  admin    2194 Mar 18 12:36 SSDT-x8_3-ApCst.dsl
> -rw-r--r--  1 steve  admin    1930 Mar 18 12:36 SSDT-x8_4-Cpu0Hwp.dsl
> -rw-r--r--  1 steve  admin    2460 Mar 18 12:36 SSDT-x8_5-ApHwp.dsl
> -rw-r--r--  1 steve  admin    2298 Mar 18 12:36 SSDT-x8_6-HwpLvt.dsl

Is that okay?

You have said:

> Open all of your dsl files from your DSDT folder. You should have pretty much the same files as me if you have the same laptop.

How am I supposed to open all of them?

Did you mean just to open DSDT.dsl?

> First apply Windows 10 Patch

Do you mean this patch?

> github.com/alexandred/VoodooI2C-Patches/blob/master/Windows/Windows_10.txt

So here is my DSDT.dsl after applying the above patch.

> https://drive.google.com/file/d/124XPd9rWkJ8Y2wlN4QOkmD2u9xH6ryzc/view?usp=sharing

so I couldn't figure this out:
http://www.mergely.com/eOIVp4k6/?vp=1

On my dsdt.dsl.
Would you please tell me which line to change.
I have multiple Method (_CRS, 0, Serialized) in different lines.

**Comment by gajjartejas** [comment]
How am I supposed to open all of them?
- Sorry, I mean to open the folder.

Did you mean just to open DSDT.dsl?
- Yes

Do you mean this patch?
Yes, apply Windows 10 Patch.

so I couldn't figure this out:
https://github.com/alexandred/VoodooI2C/blob/master/Documentation/GPIO%20Pinning.md

I have edited your file, you could use it.
[DSDT (1).dsl.zip](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/files/4350129/DSDT.1.dsl.zip)

Please read its depend on laptop

**Comment by Stevemoretz** [comment]
Hi thank you so much!
I did compile,there was no error just a couple of warnings.
So I saved it as aml and put in the patched folder.
VoodooPS2Controller was installed and my keyboard is working that's how I'm typing right now.

Only VoodooI2C.kext and VoodooI2CELAN.kext was placed in efi/clover/kexts/other

And I restarted my touchpad isn't working yet.

**Comment by Stevemoretz** [comment]
Here's the complied version :
https://drive.google.com/file/d/1ynlpzQvY7zinGaN-VaTEqYXK6UtAqXV1/view?usp=sharing

**Comment by Stevemoretz** [comment]
https://drive.google.com/file/d/1db-gdwmex_s59l4W0-_SxYPjwrszrj3u/view?usp=sharing

Here's my efi folder before I do this.

Do you think an extra kext is causing the issue?I think I have also voodooPs2Trackpad installed.

Would you please take a look and tell me what to delete for touchpad?

**Comment by Stevemoretz** [comment]
@gajjartejas Hi again do you have any idea about what's wrong I don't know i2c kext is added and loaded what's going wrong?Why nothing happens on my touchpad yet

**Comment by gajjartejas** [comment]
Hello @Stevemoretz  I have limited knowledge about ACPI patching. You can post on https://gitter.im/alexandred/VoodooI2C or follow step: https://github.com/alexandred/VoodooI2C/blob/master/Documentation/Installation.md
