### ISSUE TITLE
Don't appear ''Install Macos Catalina" on clover boot system 

### ISSUE THREAD

**Issue by edivergis** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#17]
I did the installation guide step by step and copied folder clover 10.5.3 and overwrote EFI/CLOVER, however when starting the system the installation option does not appear. Could you help me, please?

Thanks advance!

**Comment by gajjartejas** [comment]
Hello @edivergis there are couples of reason.
1. Make a sure secure boot is disabled from BIOS and UEFI boot is on
2. Try with default clover and check it is working or not
3. Make a sure folder structure is proper you had copied. You have to install clover first and then delete clover folder and copy my clover folder.
