### ISSUE TITLE
Can I try this on 310-15IKB?

### ISSUE THREAD

**Issue by wisfor** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#18]
Can I try installing macOS on my lenovo ideapad 310-15IKB?
I am going to take a look on this code, in case of need I will change it, and test it.
Let me know what will/won't work, if you know.
Specs:
CPU: Intel Core i5-7200U @ 2.50Ghz
RAM: 6GB DDR4
GPU1: Intel HD Graphics 620 - 512MB VRAM
GPU2: NVidia GeForce 920MX - 2GB DDR4 VRAM

In case of any other questions, just ask me.

NOTE: I am very tired and am writing this in hurry, might change l8r.

**Comment by gajjartejas** [comment]
You have 7th generation processor. Couples of things won't work. Like 
- Intel hd graphics, you would have to change device ID. (GeForce 920 MX never works)
- You have to change audio layout id
- Trackpad I am not sure which trackpad you have.

**Comment by wisfor** [comment]
Thanks! So if I use this repo to install macOS, and change device ID and audio layout ID, will everything else work? I don't use trackpad, I only use mouse

**Comment by gajjartejas** [comment]
Yes,

Edit: Intel WiFi will not work, see first issue.

**Comment by wisfor** [comment]
Yeah, I have some Wi-Fi adapter that might work. Thanks a lot!
