### ISSUE TITLE
OpenCore

### ISSUE THREAD

**Issue by VincentAA** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#19]
Have u tried to use OpenCore to boot? It's really hard to get it working if u tried would be great to look at ur settings

**Comment by gajjartejas** [comment]
Not tried but I will try tomorrow.

**Comment by VincentAA** [comment]
What's up, did u manage to make opencore config?

**Comment by gajjartejas** [comment]
Opencore working but laptop touchpad, brightness not working.

**Comment by VincentAA** [comment]
Please share the efi files?

**Comment by gajjartejas** [comment]
I will upload it shortly.

**Comment by VincentAA** [comment]
i think the touchpad and brightness can be fixed by patching the ssdt

**Comment by gajjartejas** [comment]
[OC 2.zip](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/files/4439857/OC.2.zip)

I have attached opencore folder.

Things are pending;
1. ACPI and DSDT patches 
2. Kernal and kext patches.

This will erase your NVRAM.

**Comment by VincentAA** [comment]
I have been trying to install Catalina 10.15.4 with it but I get black screen after 100% installer progress, and when I restart manually I get "an error occurred while verifying firmware" :/

**Comment by gajjartejas** [comment]
The above oc folder is for only post-install. You can modify according to your needs.

**Comment by VincentAA** [comment]
What's the config should look like for installation I've been trying for the past 3 days xd

**Comment by gajjartejas** [comment]
You can check the official guide it's pretty easy:
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/opencore-efi
