### ISSUE TITLE
Guide Install 

### ISSUE THREAD

**Issue by AllanLinux** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#2]
Hi
Do you have a Mojave installation guide on the Ideapad 320?

**Comment by gajjartejas** [comment]
Will be done as soon as possible.

**Comment by gajjartejas** [comment]
The partial guide added including audio, graphics.

**Comment by aravi365** [comment]
Can you please make it in a more detailed way? (Step by step) it will be helpful for many.

**Comment by gajjartejas** [comment]
Sure @aravi365

**Comment by gajjartejas** [comment]
@aravi365 Beginners guide added.

**Comment by oiboiraporteur** [comment]
Thank you for your guides. You are top!
