### ISSUE TITLE
Freeze in loading Apple

### ISSUE THREAD

**Issue by Brozinga** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#21]
I'm install Catalina, and is freezing in 100% loading apple loading screen

My PC is Core i5 7200U, 8GB DDR4, 1TB - ideapad 320 - 15lkb 80YH0006BR

Sorry my bad english, and tanks..

**Comment by gajjartejas** [comment]
Please follow this guide: https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/INSTALLATION_GUIDE_BEGINNERS.md

1. From Clover configurator Add Boot Flag(From Boot->Arguments): 

```-v```

2.  Change Your graphics property as below

 ```From Devices -> PciRoot(0x0)/Pci(0x2,0x0):```

```
Properties Key: Properties Value (Value Type: DATA)

AAPL, ig-platform-id: 59160000
framebuffer-fbmem : 00000000
framebuffer-patch-enable: 01000000
framebuffer-stolenmem: 00008800
framebuffer-unifiedmem: 00000060
```

You should remove other properties from my list if exists
