### ISSUE TITLE
WiFi Hardware

### ISSUE THREAD

**Issue by mteguhfh** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#22]
is there any way to replace wifi hardware instead of wifi stick ?

thank you

**Comment by gajjartejas** [comment]
Have you read guide link on front page?
https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/blob/master/WIRELESS_CARD_BUYING_GUIDE.md

**Comment by mteguhfh** [comment]
woa thanks, but still in doubt, with the lite-on one

**Comment by gajjartejas** [comment]
What is 'lite-on' ?
