### ISSUE TITLE
Lenovo s145 compatibility

### ISSUE THREAD

**Issue by dpatel** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#23]
Does this work with Lenovo Ideapad S145 81W800E9IN 15.6-inch FHD Thin and Light Laptop (10th Gen i5-1035G1/8GB/512GB SSD/Windows 10/Microsoft Office 2019/Integrated Graphics)?

**Comment by gajjartejas** [comment]
You have a 10th generation processor. A couple of things won't work. Like

Intel HD graphics, you would have to change the device ID. (NVIDIA GeForce Graphics card never works)
You have to change audio layout id
Trackpad I am not sure which trackpad you have.
Intel WiFi will not work, see the first issue.
