### ISSUE TITLE
Credit Requesting

### ISSUE THREAD

**Issue by Ab2774** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#25]
Hi
I appreciate using my OpenCore EFI, but can you please put credit to your guide so people can know where you got the EFI from, also, asking people for donations for something you didn't actually make isn't ethical.
Have a nice day

**Comment by gajjartejas** [comment]
I have removed your efi, thanks

**Comment by gajjartejas** [comment]
I have removed you efi ler me know if you have a problem with donationa buttons.

**Comment by Ab2774** [comment]
Hi, I'm not against using my EFI, just credit me so newcomers can know the original EFI, and I'm not against asking people for donation for your other projects because it's your work, but when it comes to hackitnoshing, it's not ideal for people to donate for a folder that contains Kernel Extension you didn't make, Bootloader you didn't make and SSDTs you didn't make.
if hackitnoshing is gonna be paid, then the developers like Acidanthera should take it, because they're the reason why our machines running macOS.
Thanks

**Comment by gajjartejas** [comment]
Still you are talking about credit even if I have removed your folder? For donation, if people like they will donate it otherwise they don't and for donation buttons even GitHub can't enforce me to remove it
