### ISSUE TITLE
10.14.3 -> 10.14.4 results in a GPU-related kernel panic

### ISSUE THREAD

**Issue by btx3** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#3]
When attempting to do an upgrade from 10.14.3 to 10.14.4 (through Settings -> Software update), the system restarts as usual and a new option appears in Clover ("Boot macOS Installer from [hard drive]"). I let it boot that partition and after a while it kernel panics here:

![Slika zaslona 2019-04-06 u 18 55 02](https://user-images.githubusercontent.com/30347409/55672667-f381f180-589d-11e9-87de-8d7023820648.png)

(It's a bit blurry as I had to record a video, then screenshot it as the text passed very quickly)

Is there a way to fix this? All searches led me to changing some DVMT setting in the BIOS, however that seems to be locked by Lenovo.

**Comment by gajjartejas** [comment]
Can you please make a sure you are using latest lily and WhateverGreen kext.

**Comment by btx3** [comment]
Fixed! Updated Clover and it booted perfectly.
