### ISSUE TITLE
What's changed in version 10.14.4

### ISSUE THREAD

**Issue by VincentAA** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#4]
I have same build and same files as you but edited config.plis a little bit, I wanna know if there's files add/changed settings add/changed from 10.14.3 files, Thanks.
Btw my laptop restarts instead of sleep, does it do the same with u?

**Comment by gajjartejas** [comment]
For 10.14.4 commit I have updated Lilu.kext, Whatever Green.kext and latest clover. Mine have same problem when laptop goes to sleep
