### ISSUE TITLE
Hdd not showing in diskutility , in macOS Big Sur installation

### ISSUE THREAD

**Issue by BlueBenzene** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#43]
**Describe the bug**

**Software Info**
 macOS Version :11.0.1
 OpenCore version: latest
 List of kexts: latest Opencore build for 11.0.1

**Hardware Info**
 Your laptop model : IdeaPad 320 15ISK
 Processor: i3 6th gen

**Comment by gajjartejas** [comment]
You should change the SATA Mode selection setting to `ACHI`, and reboot, the missing drives should appear.

**Comment by BlueBenzene** [comment]
Thanks it fixed
