### ISSUE TITLE
first usb port not work on big sur

### ISSUE THREAD

**Issue by someshsrichandan** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#44]
**Describe the bug**
 A clear and concise description of what the bug is. first usb port not working but another usb port also working

**Software Info**
 macOS Version 11.0.1
 OpenCore version: latest
 List of kexts: 

**Hardware Info**
 Your laptop model : lenevo ideapad 320 15inch
 Processor:i3 6gen

**Comment by gajjartejas** [comment]
Could you please remove `USBPorts.kext` and add `USBInjectAll.kext`?

**Comment by someshsrichandan** [comment]
![Screenshot 2020-12-16 at 12 46 32 PM](https://user-images.githubusercontent.com/69620426/102360997-b8274800-3fd8-11eb-9d51-f669f7cba424.png)
![Screenshot 2020-12-16 at 12 46 02 PM](https://user-images.githubusercontent.com/69620426/102361059-cf663580-3fd8-11eb-9185-70b3fe6ce173.png)

can you please tell me where i'm wrong. i replaced the files and add them into the config.plist and reset nvram . but not worked. or can you please update the repo with a fix and i just place them into my efi .🙏🏻

**Comment by gajjartejas** [comment]
Hello, @someshsrichandan Looks fine. Could you please verify using the Hackintool tool?
![Screenshot 2021-01-05 at 11 39 05 PM](https://user-images.githubusercontent.com/14052969/103682695-34e18c80-4faf-11eb-8eff-aa650e5d8eac.png)

Let me know.

**Comment by someshsrichandan** [comment]
Bro u send me this OC.zip file then my another USB port work fine.
 Thanks Gajjartejas
