### ISSUE TITLE
HDMI port isn't working on Big Sur

### ISSUE THREAD

**Issue by someshsrichandan** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#45]

**Comment by gajjartejas** [comment]
Could you please change your SMBIOS to `MacBookPro13,1` and let me know.

**Comment by someshsrichandan** [comment]
sorry, i changed from MacBookPro13,3 to MacBookPro13,1 but not worked
![Screenshot 2020-12-16 at 8 20 53 PM](https://user-images.githubusercontent.com/69620426/102364525-8e702000-3fdc-11eb-8d6e-9cd1e6d19ba9.png)

**Comment by someshsrichandan** [comment]
Please tell me how to fix?

**Comment by gajjartejas** [comment]
Hello, @someshsrichandan  I can confirm I have already working HDMI. Could you please check below OC.zip I have attached for you?

Note: It is important to change serial no before you install.
[OC.zip](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/files/5771805/OC.zip)

let me know working or not, also check the HDMI cable.

**Comment by someshsrichandan** [comment]
Thanks, Bro send me this OC.zip file my HDMI port is fix now.
