### ISSUE TITLE
itlwm for intel wifi not working 😭. any fix? and for bluetooth any fix please.

### ISSUE THREAD

**Issue by BlueBenzene** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#46]
**Describe the bug**

**Software Info**
 macOS Version : 11.0.1
 OpenCore version: latest
 List of kexts: latest

**Hardware Info**
 Your laptop model : 320 151SK
 Processor: i3 6th

**Comment by gajjartejas** [comment]
I will look into this issue this weekend.

**Comment by gajjartejas** [comment]
Hello, @BlueBenzene As I have replaced the card with the BCM card I can not verify but you need to inject intel wifi kext. You can take a look at https://github.com/rockavoldy/Acer-E5-476G-Hackintosh

Let me know if is working so I can include your EFI and add it to the contributor's list, so it might help someone who needs it.

Thanks
