### ISSUE TITLE
can you fix Intel wifi & bluetooth.. 

### ISSUE THREAD

**Issue by someshsrichandan** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#55]
can you fix Intel wifi & bluetooth..  also see this repositories -- https://github.com/OpenIntelWireless/itlwm . In this repositories fix the intel wifi & bluetooth

**Comment by gajjartejas** [comment]
I will try this weekend 😉

**Comment by someshsrichandan** [comment]
sure.

**Comment by someshsrichandan** [comment]
Hii @gajjartejas any fix ?

**Comment by gajjartejas** [comment]
Hi @someshsrichandan Tried but macOS panic occurs, I need to try this weekend.

**Comment by someshsrichandan** [comment]
Hi @gajjartejas also use Heliport

**Comment by someshsrichandan** [comment]
Hii @gajjartejas any fix bro?

**Comment by gajjartejas** [comment]
Hi, @someshsrichandan It's fixed!
![Screenshot 2021-05-30 at 6 58 35 PM](https://user-images.githubusercontent.com/14052969/120106027-0b511980-c179-11eb-8d64-97b2ab5c8b2a.png)

**Comment by gajjartejas** [comment]
With ```AirportItlwm.kext```
![Screenshot 2021-05-30 at 7 16 02 PM](https://user-images.githubusercontent.com/14052969/120106629-7b609f00-c17b-11eb-9ee6-c236f2c11be3.png)

**Comment by tahaklkt-osxinfo** [comment]
Hello. I can't use intel wifi with airport itlwm im using opencore and catalina i want native intel wifi because heliport is very buggy.

**Comment by someshsrichandan** [comment]
Hii @gajjartejas give the oc file? let me clear its work on bigsur?

**Comment by gajjartejas** [comment]
Hi @someshsrichandan Please find a link. It is working on BigSur with Intel Card: https://ark.intel.com/content/www/us/en/ark/products/89450/intel-dual-band-wireless-ac-3165.html

OC Link:
https://file.io/3mSbSJcjGNbc

**Comment by gajjartejas** [comment]
Hi @tahaklkt-osxinfo What WiFi card you are using? What macOS version do you have?

**Comment by tahaklkt-osxinfo** [comment]
hi @gajjartejas im using intel centrino adcanced n 6235 5g opencore catalina 10.15.7.
my system is : 
intel i5 m430 arrandale
nvidia gt 330m
8 gb ram
samsung ssd
thanks.

**Comment by someshsrichandan** [comment]
Hii @gajjartejas When i place your oc file on my EFI my laptop doesn't showing checking media.

**Comment by someshsrichandan** [comment]
itlwn.kext doesn't work
![Screenshot 2021-06-02 at 12 28 37 PM](https://user-images.githubusercontent.com/69620426/120438108-8fd0b180-c39e-11eb-9258-c79362e21cb0.png)
![Screenshot 2021-06-02 at 12 03 55 PM](https://user-images.githubusercontent.com/69620426/120438175-a971f900-c39e-11eb-86e4-1d9a17420e41.png)
![Screenshot 2021-06-02 at 12 00 34 PM](https://user-images.githubusercontent.com/69620426/120438202-b393f780-c39e-11eb-9007-9b38df4b4bae.png)
![Screenshot 2021-06-02 at 12 00 51 PM](https://user-images.githubusercontent.com/69620426/120438209-b42c8e00-c39e-11eb-9a10-f4b86a52c80e.png)



![Screenshot 2021-06-02 at 12 03 33 PM](https://user-images.githubusercontent.com/69620426/120438165-a5de7200-c39e-11eb-8567-8de09242ba49.png)

**Comment by gajjartejas** [comment]
System extension is blocked. You need to search about it.

**Comment by someshsrichandan** [comment]
Hii @gajjartejas kextstat | grep -i "itlwm" this command in terminal but heliport show itlwn is not running . How to do?

**Comment by someshsrichandan** [comment]
![Screenshot 2021-06-09 at 10 33 41 PM](https://user-images.githubusercontent.com/69620426/121398514-12dfa200-c973-11eb-9518-b11bac62162d.png)

**Comment by gajjartejas** [comment]
Okay, I will check it.

**Comment by gajjartejas** [comment]
Okay, I will check it.

**Comment by gajjartejas** [comment]
Okay, I will check it.

**Comment by someshsrichandan** [comment]
Hi @gajjartejas This is my wireless cardhttps://www.realtek.com/en/products/communications-network-ics/item/rtl8821ae
*description: Wireless interface
       product: RTL8821AE 802.11ac PCIe Wireless Network Adapter
       vendor: Realtek Semiconductor Co., Ltd.

*I got this information from Ubuntu.
please send me any solution 🙏🙏

**Comment by someshsrichandan** [comment]
Let me clear which wireless card you have use & what is tha mac version & opencore version
*my mac version is 11.0.1

**Comment by gajjartejas** [comment]
Hi @someshsrichandan Realtek RTL8821AE Wifi is not supported by Hackintosh yet. However, you can buy supported parts from a local computer repair shop, they have available at a pretty cheap cost.

see: https://dortania.github.io/Wireless-Buyers-Guide/types-of-wireless-card/m2.html#supported-cards

I am using Intel `Intel® Dual Band Wireless-AC 3165` card which comes with `Lenovo Ideapad 320 15ISK` which I am using right now.

https://ark.intel.com/content/www/us/en/ark/products/89450/intel-dual-band-wireless-ac-3165.html

**Comment by someshsrichandan** [comment]
Thanks @gajjartejas i will try on intel wireless card.

**Comment by someshsrichandan** [comment]
![WhatsApp Image 2021-06-17 at 12 42 31 PM](https://user-images.githubusercontent.com/69620426/122442880-a856e380-cfbc-11eb-8b7a-e750d1d4b831.jpeg)
i will try on Intel® Dual Band Wireless-AC 3168 it's work fine thanks❤️ @gajjartejas
