### ISSUE TITLE
Hdmi audio doesn't work.

### ISSUE THREAD

**Issue by someshsrichandan** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#58]
macOS Version-- 11.0.1

Hi @gajjartejas! Hdmi audio not show in sound section please
 help.[Uploading Screenshot 2021-07-11 at 11.14.49 AM.png…]()
![Screenshot 2021-07-11 at 11 14 19 AM](https://user-images.githubusercontent.com/69620426/125184205-793d3600-e239-11eb-884e-60878fb9085e.png)
![Screenshot 2021-07-11 at 11 14 49 AM](https://user-images.githubusercontent.com/69620426/125184241-cfaa7480-e239-11eb-8be8-8be858610dd1.png)

**Comment by someshsrichandan** [comment]
Hi @gajjartejas any fix please tell me .

**Comment by gajjartejas** [comment]
Hi @someshsrichandan I will check it today.

**Comment by someshsrichandan** [comment]
Thanks @gajjartejas .

**Comment by someshsrichandan** [comment]
@gajjartejas any fix?

**Comment by gajjartejas** [comment]
Hi, @someshsrichandan Could you please check the latest release, sorry for the late reply.
