### ISSUE TITLE
Still waiting for root device

### ISSUE THREAD

**Issue by incdapp** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#6]
Notebook: Lenovo 320-15ISK

When you run the installer macOS Catalina beta 1 after a few seconds will turn off the flash drive, and then you receive an error “Still waiting for root device”, attempts to fix is not how not to help (substitution of kexts  and so on)

**Comment by gajjartejas** [comment]
Have you set SATA controller Mode to AHCI?

**Comment by incdapp** [comment]
AHCI is on, I never turn it off

**Comment by gajjartejas** [comment]
Ok I will try to reproduce it

**Comment by incdapp** [comment]
Thanks, by the way the image is fully working (installed on Acer Aspire V3-571G with another Clover)

**Comment by incdapp** [comment]
Now I don't understand. The installer was able to start. The error was that macOS disables USB ports, and then can not find a flash drive with the system image. But after several attempts to start, the system was able to start. Very strange.

**Comment by incdapp** [comment]
Although there is no, all also "Still waiting for root device”

**Comment by incdapp** [comment]
I found a bug, if you remove the DSDT, all works, what it involves I don't know

**Comment by gajjartejas** [comment]
Thanks for informing. I will remove DSDT from clover.
