### ISSUE TITLE
Not an issue: What's the touchpad like now?

### ISSUE THREAD

**Issue by btx3** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#7]
Hi,

I used to have macOS installed, but I had to reinstall Windows because I could not use the touchpad properly (it was very janky).

I've seen that in commit 803409461d15632e790c3d6d3e81772652350e90 the guide was changed, now also including VoodooI2C.kext. Does this make the touchpad work like on Windows/Linux now? Or is it still the same?

**Comment by gajjartejas** [comment]
Now, touchpad is fully supported. Including gestures

**Comment by gajjartejas** [comment]
Like windows

**Comment by btx3** [comment]
Awesome! Thank you.
