### ISSUE TITLE
Ethernet card not showing...

### ISSUE THREAD

**Issue by someshsrichandan** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#70]
**Describe the bug**

**Software Info**
 macOS Version 11.0.1
 
I use secondary hhd and boot monetary ethernet works properly but in bigsur it doesn't works , what to do .. ( also modified the RealtekRTL8111.kext but doesn't work)
![IMG_20221121_205813.jpg](https://user-images.githubusercontent.com/69620426/203094214-7691b55d-2d99-409c-9fb4-f8addedec0d6.jpg)

**Comment by gajjartejas** [comment]
Hi, @someshsrichandan Could you please provide your ethernet card specification/info?

**Comment by someshsrichandan** [comment]
> Hi, @someshsrichandan Could you please provide your ethernet card specification/info?

![IMG_20221123_092751.jpg](https://user-images.githubusercontent.com/69620426/203466618-65d87efd-3778-4fa7-9a57-b0852512611a.jpg)

I use accer 515 EFI 😅 successful boot and ethernet only work and a lots of issues...
