### ISSUE TITLE
WiFi Causing Freezing, Lagging MacOS / MacOS BigSur 11.7.4

### ISSUE THREAD

**Issue by Cyosai** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#71]
Help me, please. How to disable WiFi completely forever, to not work after restarting MacOS? To prevent this MacOS Freezing, Lagging problem.
I'm using Ethernet Cable.

I'm attached my OpenCore EFI Folder.
-- https://mega.nz/file/yBh31KoK#HX1wJssruLNU2yZcGNF8jqS5o1BbfYWvk-gbW6QwF1A

**Comment by gajjartejas** [comment]
You can disable wifi from entering bios and turning off wireless options.

**Comment by Cyosai** [comment]
Gajjartejas thank you for answering my question and helping me. Can I also ask you how to disable the internal keyboard and use an external one instead in macos big sur?
