### ISSUE TITLE
"Kexts used" links

### ISSUE THREAD

**Issue by Mojiberus** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#75]
In the "kexts used" section `restrictevents.kext` moves you to https://github.com/Mieze/RTL8111_driver_for_OS_X, which is a link to prevoius kext
![image](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/assets/63734948/1abedc9e-df01-4eae-972b-805749b0c4b6)

**Comment by gajjartejas** [comment]
Thank you for your valuable feedback, I will correct it.
