### ISSUE TITLE
Is It Possible To Get The Stock WIFI card Working(QCA9377)

### ISSUE THREAD

**Issue by TechyStark7** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#77]
Hi @gajjartejas ,I just installed Hackintosh In my ideapad320 everything is working except WIFI. So is there any way for getting the WIFI working,

**Comment by gajjartejas** [comment]
Hi @TechyStark7 Qualcomm Atheros cards are not supported, check supported Wi-Fi cards here: https://dortania.github.io/Wireless-Buyers-Guide/unsupported.html#supported-chipsets

**Comment by TechyStark7** [comment]
@gajjartejas, I thought there was some way using some kexts. Anyway Thank You....
