### ISSUE TITLE
Sleep fully working

### ISSUE THREAD

**Issue by btx3** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#8]
Hi, so I’ve been trying to get sleep working on this machine. I’ve successfully fixed the power management ([ssdtPRGen.sh](https://github.com/Piker-Alpha/ssdtPRGen.sh) and [freqVectorsEdit.sh](https://github.com/Piker-Alpha/freqVectorsEdit.sh)), the post-wake lag ([VoodooTSCSync](https://github.com/RehabMan/VoodooTSCSync)) and the instant wake for the reason „GLAN XDCI“ (DSDT patch according to [this post](https://www.tonymacx86.com/threads/instant-wake-from-sleep-wake-reason-glan-xdci-skylake-el-capitan.198588/post-1342082)).

The issue I’m facing now is another instant wake problem, this time the reason being „XDCI XHC“, which, according to [this](https://www.tonymacx86.com/threads/sleep-wake-cycling-forever-wake-reason-xdci.249480/) post, is an issue with the USB port mapping/setup. The problem is, I have no idea how this is set up, and the guide is way too complicated, at least for me (also my touchpad stopped working after applying the patches, so I had to revert them).

Posting this here for now, will report back if I manage to fix it.

**Comment by btx3** [comment]
Applied the "USB _PRW 0x6D Skylake (instant wake)" patches to the DSDT, sleep works completely now!

**Comment by gajjartejas** [comment]
Thank you, I will include in the guide.
