### ISSUE TITLE
I will Share My SSDT-I2C.aml with you  Enjoy

### ISSUE THREAD

**Issue by ameenjuz** [gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh#9]
please add this SSDT-I2C.aml Patches and KextToPatch in your repo
first of all test it if you satisfy then uploader on your repo
I confirmed 100% working
I attached all require file make sure you have installed VoodooI2C.kext+VoodooI2CELAN.kext
[SSDT-I2C.zip](https://github.com/gajjartejas/Lenovo-Ideapad-320-15ISK-14ISK-Laptop-Hackintosh/files/3628881/SSDT-I2C.zip)
 v2.2

**Comment by gajjartejas** [comment]
Thanks for patch. I wii check it.

**Comment by gajjartejas** [comment]
@ameenjuz I have checked your SSDT-I2C hotpatch, Also your repo looks amazing. The brightness key also works.

I have one question can you please tell me how you generated SSDT hot patches?

**Comment by iamtushar324** [comment]
where to put these files please tell me my trackpad and brightness not working
